#!/usr/bin/env sh
set -e

pnpm --filter @ets-vibes/desktop check-types

cargo clippy \
  --workspace \
  --all-targets \
  --all-features \
  --locked \
  -- \
  -D warnings

cargo fmt --all --check

cargo test \
  --workspace \
  --all-features \
  --locked